# Generated by Django 6.0.6 on 2026-07-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название курса")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="courses_previews", verbose_name="Превью курса"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание курса")),
                ("usd_price", models.PositiveIntegerField(verbose_name="Стоимость подписки на курс в центах USD")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название урока")),
                ("description", models.TextField(verbose_name="Описание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="lessons_previews", verbose_name="Превью урока"
                    ),
                ),
                ("link_to_video", models.URLField(blank=True, null=True, verbose_name="Ссылка на видео")),
                ("usd_price", models.PositiveIntegerField(verbose_name="Стоимость отдельного урока в центах USD")),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата платежа")),
                ("amount", models.PositiveIntegerField(verbose_name="Сумма платежа")),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "Наличными"), ("cashless", "Перевод")],
                        max_length=8,
                        verbose_name="Способ оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_product_id",
                    models.CharField(max_length=255, unique=True, verbose_name="id продукта в Stripe"),
                ),
                ("stripe_price_id", models.CharField(max_length=255, verbose_name="id цены в Stripe")),
                ("is_active", models.BooleanField(default=True, verbose_name="Статус актуальности")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "product_type",
                    models.CharField(
                        choices=[("course", "Курс"), ("lesson", "Урок")], max_length=6, verbose_name="Тип продукта"
                    ),
                ),
                ("product_name", models.CharField(max_length=200, verbose_name="Название продукта")),
                ("product_price", models.PositiveIntegerField(verbose_name="Цена продукта")),
                ("owner_id", models.PositiveIntegerField(verbose_name="id пользователя-владельца")),
                ("owner_email", models.EmailField(max_length=254, verbose_name="Адрес электронной почты владельца")),
            ],
            options={
                "verbose_name": "Stripe-идентификатор",
                "verbose_name_plural": "Stripe-идентификаторы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
                "ordering": ["course", "subscriber"],
            },
        ),
    ]
