# Generated by Django 6.0.6 on 2026-06-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название курса")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="courses_previews", verbose_name="Превью курса"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание курса")),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название урока")),
                ("description", models.TextField(verbose_name="Описание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="lessons_previews", verbose_name="Превью урока"
                    ),
                ),
                ("link_to_video", models.URLField(blank=True, null=True, verbose_name="Ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="education.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
        ),
    ]
