# Generated by Django 6.0.6 on 2026-07-07 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("education", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="education.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Плательщик",
            ),
        ),
        migrations.AddField(
            model_name="stripeproduct",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stripe_courses",
                to="education.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="stripeproduct",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stripe_lessons",
                to="education.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="education.stripeproduct",
                verbose_name="Оплаченный продукт",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accessions",
                to="education.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчик",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("subscriber", "course")},
        ),
    ]
