# Generated by Django 6.0.6 on 2026-07-08 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.CharField(max_length=255, unique=True, verbose_name="Идентификатор сессии")),
                ("session_url", models.URLField(max_length=500, verbose_name="Ссылка на оплату")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыта"), ("complete", "Завершена"), ("expired", "Просрочена")],
                        default="open",
                        max_length=8,
                        verbose_name="Статус сессии",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Заказчик",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_sessions",
                        to="education.stripeproduct",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe-сессия",
                "verbose_name_plural": "Stripe-сессии",
                "ordering": ["-status"],
            },
        ),
    ]
