# Generated by Django 6.0.6 on 2026-07-09 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_stripesession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stripe_payments",
                to="education.stripeproduct",
                verbose_name="Оплаченный продукт",
            ),
        ),
    ]
