# Generated by Django 6.0.6 on 2026-07-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_alter_payment_stripe_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(verbose_name="Дата платежа"),
        ),
    ]
